version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web/ponte-console
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
