<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Ingestion\Ponte.Ingestion.Api\Ponte.Ingestion.Api.csproj" />
  </ItemGroup>
</Project>
