<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Ponte.BuildingBlocks\Ponte.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
