<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Delivery\Ponte.Delivery.Api\Ponte.Delivery.Api.csproj" />
  </ItemGroup>
</Project>
